### ISSUE TITLE
Same java package name as react-native-wheel-picker

### ISSUE THREAD

**Issue by nvojnovic** [pinguinjkeke/react-native-wheel-picker#19]
Because android java package names are the same in both projects "com.zyu" they can't be used together in one project. Build is failing with error "more than one library with package name 'com.zyu'".

**Comment by pinguinjkeke** [comment]
Hello. Can you provide an example? You can email me with code archive or use something like expo

**Comment by nvojnovic** [comment]
After unlinking react-native-wheel-datepicker project builds but then react native is complaining about "Tried register two views with the same name WheelCurvedPicker". Which is done in WheelCurvedPicker.android.js
`const WheelCurvedPickerNative = requireNativeComponent('WheelCurvedPicker', WheelCurvedPicker);`

**Comment by nvojnovic** [comment]
Ok, removed react-native-wheel-picker from my dependencies and using Picker component from react-native-wheel-datepicker.
Anyway, it's not good to just copy code from other libraries because it will lead to problem like this.

**Comment by pinguinjkeke** [comment]
@nvojnovic it's not a copy, it's a fork which moved to separate repository because of all PRs goes to repository which is not maintained (you can read it in history inside project's README.md).

It's a plan to rewrite Java part and upgrade to latest WheelCurvedPicker and I'll change namespace.


Thank you for feedback

**Comment by nvojnovic** [comment]
@pinguinjkeke sorry, I didn't express myself properly.
I was just pointing out to possible issues when combining those two libraries in the same project.

Keep up the good work.
