### ISSUE TITLE
Change Color of indicator Lines

### ISSUE THREAD

**Issue by mlanders3** [pinguinjkeke/react-native-wheel-picker#22]
How can the color of the indicator lines be changed?

**Comment by mikaello** [comment]
I don't think there is an option for this as of now. In our project we ended up forking this module and changing the color in the Android code to make it similar to iOS: https://github.com/kievu/react-native-wheel-datepicker/commit/96a861d5278ab0a668d0bb0471fac02161e84757 . See also issue #11
